class KeyMustBeStr(Exception): ...
class KeyAddError(Exception): ...
class KeyNotFound(Exception): ...
class UnkownTag(Exception): ...
class ValueIsConstant(Exception): ...
class ForeignKeyError(Exception): ...
class UniqueValueError(Exception): ...
class UpdateDenied(Exception): ...